title: "Notas de um Praticante de Psicanálise"
email: contato@exemplo.com
description: "Blog pessoal e profissional sobre psicanálise e terapia."
url: "https://jeffsouzaoficial.github.io"
baseurl: "/blog-psi"
plugins:
  - jekyll-feed

# Build settings
permalink: /posts/:title/

# Exclude
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor